#! /bin/sh

# just a helper file to quickly symlink the shit in this repo

ln -s .config/systemd/ ~/.config/systemd
ln -s .config/termite  ~/.config/termite
ln -s .config/omf      ~/.config/omf 
ln -s .config/fish     ~/.config/fish
